import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Poppins", "Inter", "sans-serif"],
      },
      colors: {
        // AarogyaMitra Color Palette
        herbal: {
          DEFAULT: "#2F7E79",
          50: "#E8F4F3",
          100: "#D1E9E7",
          200: "#A3D3CF",
          300: "#75BDB7",
          400: "#47A79F",
          500: "#2F7E79",
          600: "#256662",
          700: "#1B4D4A",
          800: "#113331",
          900: "#081A19",
        },
        sand: {
          DEFAULT: "#F9F8F4",
          50: "#FEFEFE",
          100: "#F9F8F4",
          200: "#F3F1E9",
          300: "#EDEADE",
          400: "#E7E3D3",
          500: "#E1DCC8",
          600: "#DBD5BD",
          700: "#D5CEB2",
          800: "#CFC7A7",
          900: "#C9C09C",
        },
        coral: {
          DEFAULT: "#EF8354",
          50: "#FDF5F2",
          100: "#FBEBE5",
          200: "#F7D7CB",
          300: "#F3C3B1",
          400: "#EFA397",
          500: "#EF8354",
          600: "#EC6A2C",
          700: "#D85820",
          800: "#B04619",
          900: "#883412",
        },
        indigo: {
          DEFAULT: "#394867",
          50: "#EEF0F3",
          100: "#DDE1E7",
          200: "#BBC3CF",
          300: "#99A5B7",
          400: "#77879F",
          500: "#556987",
          600: "#394867",
          700: "#2D3A52",
          800: "#212C3D",
          900: "#151E28",
        },
        softred: {
          DEFAULT: "#F06C6C",
          50: "#FDF2F2",
          100: "#FBE5E5",
          200: "#F7CBCB",
          300: "#F3B1B1",
          400: "#EF9797",
          500: "#F06C6C",
          600: "#ED4747",
          700: "#E12222",
          800: "#B91B1B",
          900: "#911414",
        },
        genderblue: {
          DEFAULT: "#3E8EDE",
          50: "#EFF6FE",
          100: "#DFEDFD",
          200: "#BFDBFB",
          300: "#9FC9F9",
          400: "#7FB7F7",
          500: "#5FA5F5",
          600: "#3E8EDE",
          700: "#2470B8",
          800: "#1D5A93",
          900: "#16446E",
        },
        genderpink: {
          DEFAULT: "#DE6EA1",
          50: "#FDF2F8",
          100: "#FBE5F1",
          200: "#F7CBE3",
          300: "#F3B1D5",
          400: "#EF97C7",
          500: "#EB7DB9",
          600: "#DE6EA1",
          700: "#D15A89",
          800: "#A84671",
          900: "#7F3359",
        },
        grayborder: {
          DEFAULT: "#DADADA",
          50: "#F8F8F8",
          100: "#F1F1F1",
          200: "#EAEAEA",
          300: "#E3E3E3",
          400: "#DCDCDC",
          500: "#DADADA",
          600: "#C8C8C8",
          700: "#B6B6B6",
          800: "#A4A4A4",
          900: "#929292",
        },
        // Keep existing Shadcn colors for compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
